BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[entries] (
    [id] INT NOT NULL IDENTITY(1,1),
    [title] NVARCHAR(255) NOT NULL,
    [date] NVARCHAR(50) NOT NULL,
    [summary] NVARCHAR(1000) NOT NULL,
    [tags] NVARCHAR(1000) NOT NULL,
    [mood] NVARCHAR(255) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [entries_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [entries_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
